### PR TITLE
Fix typo in postgresql_setup

### PR DESCRIPTION
**Pull request by kristoff3r**
Thanks for making this, it is a good source of inspiration for a similar setup I'm making. Your last commit introduced a typo which gives a very weird error message, so I thought I would upstream it just to spare others from debugging that :D

Also, elixir_1_10 doesn't exist in the pinned nixpkgs you use, so you should probably bump that or revert to elixir_1_9.

### CODE REVIEW

**Comment by happysalada** [comment]
@cw789 you might want to have a look at this when you have some time.

**Comment by cw789** [comment]
Hey, thanks @kristoff3r. That PR did completely passed my be. Sorry.

@happysalada
Of course. I watched your issue "RFC fixing build-mix" in `nixpkgs` and I'm doing right now a bit or refactoring this demo repo.
Give my some weeks and everything will be up.

**Comment by happysalada** [comment]
This repo is really awesome, thanks again for making it!

**Comment by cw789** [comment]
This fix is integrated now but there is still a lot of things in a state of work in progress...
→ Noted it down here: https://github.com/cw789/elixir_nix_seed/issues/2

Hope I'll address this things soon, to have again a great workable example repo.

**Pull request closed without merging**
